name: Microsoft.IoT.Devices
description: Helper library for interfacing with devices in Windows IoT projects.
markdown: redcarpet
pygments: true
permalink: pretty
baseurl: /iot-devices
repourl: https://github.com/jbienzms/iot-devices
